postgis_ros_publisher:
  ros__parameters:

    postgresql:
      user: "postgres"
      pass: "postgres" # TODO: Alternative way w/o need of storing password in plaintext
      host: "L1AS17"
      port: 5432
      schema: "test"

    publish:
      - cfg_point
      - cfg_road
      - cfg_building

    cfg_default:
      rate: 10.0

    cfg_road: 
      query: "SELECT id, geom AS geometry FROM road;"
      # frame_id: "asdf" # custom or via frame_id
      topic: "marker_array"
      frame_id: "map"
      type: "MarkerArray"
      # marker_type: "visualization_msgs::Marker::LINE_STRIP" 
      marker_scale: [1.0, 1.0, 1.0]
      
      utm_transform: true
      utm_offset:
        lat: "16.511422682732736"
        lon: "47.977274686327114"

      rate: 1.0

    cfg_building: 
      query: "SELECT id, geom AS geometry FROM building;"
      # frame_id: "asdf" # custom or via frame_id
      topic: "marker_array"
      frame_id: "map"
      type: "MarkerArray"
      # marker_type: "visualization_msgs::Marker::LINE_STRIP" 
      marker_ns: "buildings"
      marker_color: [0.0, 1.0, 0.0, 1.0]
      utm_transform: true
      marker_scale: [1.0, 1.0, 1.0]
      utm_offset:
        lat: "16.511422682732736"
        lon: "47.977274686327114"

      rate: 1.0

    cfg_point: 
      query: "SELECT id, geom AS geometry, 'map' AS frame_id FROM landmark;"
      type: "MarkerArray" # Point2D PointCloud, Polygon Marker, Marker, Pose 
      # frame_id: "asdf" # custom or via frame_id
      topic: "marker_array"
      

      marker_type: "visualization_msgs::Marker::SPHERE"  
      marker_ns: "landmarks"
      marker_scale: [2.0, 2.0, 2.0]
      frame_id: "map"

      utm_transform: true
      utm_offset:
        lat: "16.511422682732736"
        lon: "47.977274686327114"
      rate: 1.0