postgis_ros_publisher:
  ros__parameters:

    postgresql:
      user: "postgres"
      pass: "postgres" # TODO: Alternative way w/o need of storing password in plaintext
      host: "localhost"
      port: 5432
      schema: "postgres_alchemy_ait"

    publish:
      - cfg_point
      # - cfg_marker
      # - cfg_pointcloud
      # - cfg_pose 

    cfg_default:
      rate: 10.0

    cfg_point: 
      query: "SELECT position AS geometry, 'test_frame_id' AS frame_id FROM landmark;"
      type: "Point3D" # Point2D PointCloud, Polygon Marker, Marker, Pose 
      # frame_id: "asdf" # custom or via frame_id
      topic: "point"
      rate: 10.0


    cfg_marker: 
      query: "SELECT position AS geometry, 'test_frame_id' AS frame_id FROM landmark;"
      type: "Marker"
      position: "asdf" #automatic with geometry
      orientation: "asdf" # autmatic with orientation (rpy) else 0
      marker_type: "visualization_msgs::Marker::SPHERE" # marker_type or here | default sphere

    cfg_pointcloud:
      query: "SELECT position AS geometry FROM landmark;"
      type: "PointCloud2"
      frame_id: "test_frame_id" # custom
      rate: 1.0

    cfg_pose: 
      query: "SELECT landmark.position AS geometry, landmark.orientation as orientation, 'test_frame_id' AS frame_id FROM landmark;"
      type: "Pose"
      position: "asdf" # geometry
      orientation: "asdf" # orientation (xyz as rpy, which is as geometry)


      # frame_id: "map" 
      # rate: 10



# "SELECT ST_MakePolygon( 'LINESTRING(75.15 29.53 1,77 29 1,77.6 29.5 1, 75.15 29.53 1)') AS geometry, ST_GeometryType(ST_MakePolygon( 'LINESTRING(75.15 29.53 1,77 29 1,77.6 29.5 1, 75.15 29.53 1)')) AS type, 'test' AS frame_id;"
# "SELECT ST_MakePoint(10.15, 13.53, 0.0) AS geometry, ST_GeometryType(ST_MakePoint(10.15, 13.53, 0.0)) AS type, 'test' AS frame_id;"
# "SELECT ST_MakePoint(75.15, 29.53, 1.0) AS geometry, ST_GeometryType(ST_MakePoint(75.15, 29.53, 1.0)) AS type, 'test' AS frame_id;"