postgis_ros_publisher:
  ros__parameters:
    postgresql:
      user: "postgres"
      pass: "postgres" # TODO: Alternative way w/o need of storing password in plaintext
      host: "localhost"
      port: 5432
      schema: "postgres_alchemy_ait"

    publish:
      - cfg_point
      - cfg_marker
      - cfg_marker_array
      - cfg_pointcloud
      - cfg_pose
      - cfg_pose_array
      - cfg_pose_stamped
      - cfg_polygon
      - cfg_polygon_stamped

    cfg_default:
      rate: 10.0

    cfg_point:
      query: "SELECT position AS geometry, 'test_frame_id' AS frame_id FROM landmark;"
      type: "PointStamped" 
      topic: "point"
      rate: 10.0

    cfg_marker:
      query: "SELECT ROW_NUMBER() OVER (ORDER BY pose.id) AS id, pose.position AS geometry, pose.rotation_vector AS rotation, 'test_frame_id' AS frame_id FROM pose;"
      type: "Marker"
      marker_type: "visualization_msgs::Marker::SPHERE" # marker_type or here | default sphere
      topic: "marker"
      rate: 10.0

    cfg_marker_array:
      query: "SELECT ROW_NUMBER() OVER (ORDER BY pose.id) AS id, pose.position AS geometry, pose.rotation_vector AS rotation, 'test_frame_id' AS frame_id FROM pose;"
      type: "MarkerArray"
      marker_type: "visualization_msgs::Marker::SPHERE" # marker_type or here | default sphere
      topic: "marker_array"
      frame_id: "test_frame_id" # custom
      rate: 10.0

    cfg_pointcloud:
      query: "SELECT position AS geometry FROM landmark;"
      type: "PointCloud2"
      frame_id: "test_frame_id" # custom
      topic: "pointcloud"
      rate: 1.0

    cfg_pose:
      query: "SELECT pose.position AS geometry, pose.rotation_vector AS rotation FROM pose;"
      type: "Pose"
      topic: "pose"
      rate: 10.0

    cfg_pose_array:
      query: "SELECT pose.position AS geometry, pose.rotation_vector AS rotation FROM pose;"
      type: "PoseArray"
      topic: "pose_array"
      frame_id: "test_frame_id"
      rate: 10.0

    cfg_pose_stamped:
      query: "SELECT pose.position AS geometry, pose.rotation_vector AS rotation, 'test_frame_id' AS frame_id FROM pose;"
      type: "PoseStamped"
      topic: "pose_stamped"
      rate: 10.0

    cfg_polygon:
      query: "SELECT ST_MakePolygon( 'LINESTRING(75.15 29.53, 77 29, 77.6 29.5, 75.15 29.53)') AS geometry, ST_GeometryType(ST_MakePolygon( 'LINESTRING(75.15 29.53 1,77 29 1,77.6 29.5 1, 75.15 29.53 1)')) AS type, 'test' AS frame_id;"
      type: "Polygon"
      topic: "polygon"
      rate: 10.0

    cfg_polygon_stamped:
      query: "SELECT ST_MakePolygon( 'LINESTRING(75.15 29.53 1,77 29 1,77.6 29.5 1, 75.15 29.53 1)') AS geometry, ST_GeometryType(ST_MakePolygon( 'LINESTRING(75.15 29.53 1,77 29 1,77.6 29.5 1, 75.15 29.53 1)')) AS type, 'test' AS frame_id;"
      type: "PolygonStamped"
      topic: "polygon_stamped"
      frame_id: "test_frame_id"
      rate: 10.0

      # frame_id: "map"
      # rate: 10
# "SELECT ST_MakePolygon( 'LINESTRING(75.15 29.53 1.0, 77 29 1,77.6 29.5 1.0 , 75.15 29.53 1.0 )') AS geometry, ST_GeometryType(ST_MakePolygon( 'LINESTRING(75.15 29.53 1,77 29 1,77.6 29.5 1, 75.15 29.53 1)')) AS type, 'test' AS frame_id;"
# "SELECT ST_MakePoint(10.15, 13.53, 0.0) AS geometry, ST_GeometryType(ST_MakePoint(10.15, 13.53, 0.0)) AS type, 'test' AS frame_id;"
# "SELECT ST_MakePoint(75.15, 29.53, 1.0) AS geometry, ST_GeometryType(ST_MakePoint(75.15, 29.53, 1.0)) AS type, 'test' AS frame_id;"
